### ISSUE TITLE
Getter:peek () is weird!

### ISSUE THREAD

**Issue by gvvaughan** [stevedonovan/LuaMacro#5]
Hi Steve,

It makes sense to me that `get:peek (n, true)` counts spaces and comment tokens, and that since you can't predict what space and comment tokens might be in the input, why that is not the default.

But, with only one argument, peek is behaving weird… apparently space tokens are not filled in correctly, containing a copy of a neighbouring token, but taking up space in the 'skipped' token stream anyway. Is this a bug, or am I not understanding how it works?

```lua
local macro = require "macro"

macro.define ('target', function (get)
  local i = 0
  repeat
    i = i + 1
    local tk, v = get:peek (i, true)
    local tk_, v_ = get:peek (i)
    print (i, tk, v, tk_, v_)
  until v == " EOS"
  return nil, true
end)

macro.substitute [[
  target foo = "bar", function (t) -- comment
    print "test"
  end
]]
```

What I'd like to do is check whether the 2nd non-space. non-comment token is an "=" before expanding the macro, but that token is always 3 peek positions forward, irrespective of dont_skip mode (unless of course the unexpanded text has different spacing to my example).it seems like 1-argument peek ought to be able to do this?

Ideally, I'd then like to preserve line-breaks as I copy the remaining tokens to the output,  injecting some other missing lua syntax as I go. peek with true as the second argument seems like it will let me detect and copy whitespace once I get past the first issue?

Cheers!

**Comment by stevedonovan** [comment]
All I can say is yes, `peek` is a weird method.  Let me have a look this
weekend.

**Comment by gvvaughan** [comment]
The code above, and the macro I am writing are working with #6.

Unless I'm grossly misunderstanding how peek is designed to be used, this seems like the right approach to me.
